from snakemake.utils import min_version

##### set minimum snakemake version #####
min_version("6.15.0")


##### setup report #####
configfile: "config/config.yaml"


##### load rules #####
include: "rules/common.smk"
include: "rules/trimming_se.smk"
include: "rules/trimming_pe.smk"
include: "rules/alignment.smk"
include: "rules/samtools.smk"
include: "rules/picard.smk"
include: "rules/bqsr.smk"


##### local rules #####
localrules: all, pre_rename_fastq_pe, post_rename_fastq_pe

##### target rules #####
rule all:
    input:
        expand(resolve_results_filepath(config.get("paths").get("results_dir"),"reads/recalibrated/{sample.sample}.dedup.recal.bam"),sample=samples.reset_index().itertuples())
