language: python
python:
- 3.6
- 3.7
- 3.8
- 3.9

install:
- sudo apt-get update
- wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda config --add channels bioconda
- conda config --add channels conda-forge
- conda update -q conda
- conda info -a
- conda install mamba -c conda-forge
- mamba create -q -n test-env python=$TRAVIS_PYTHON_VERSION
- mamba env update -q -n test-env --file environment.yaml
- conda activate test-env
- export TEST_ROOT=$PWD/test
- wget https://github.com/solida-core/test-data-DNA/archive/main.zip
- if [ -f "main.zip" ]; then unzip main.zip && mv test-data-DNA-main/data $TEST_ROOT && rm -f main.zip && rm -rf test-data-DNA-main; fi
- if [ -f "$TEST_ROOT/data/references/ucsc/hg19/known_variants/dbSNP146_chr22.vcf.gz" ]; then gunzip -k $TEST_ROOT/data/references/ucsc/hg19/known_variants/*.gz; fi

script:
  - snakemake --snakefile Snakefile --configfile test/files/config.test.yaml --use-conda -n --quiet -d test/workdir
  - snakemake --snakefile Snakefile --configfile test/files/config.test.yaml --use-conda --conda-frontend mamba --cores all --quiet -d test/workdir