language: python
python:
- 3.6
- 3.8

install:
- sudo apt-get update
- wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda config --add channels bioconda
- conda config --add channels conda-forge
- conda update -q conda
- conda info -a
- conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
- conda env update -q -n test-environment --file environment.yaml
- source activate test-environment

script:
  - snakemake --snakefile Snakefile --configfile test_data/config.test.yaml --use-conda --dryrun -d folder_test
