# path or URL to sample sheet (TSV format, columns: sample, condition, ...)
samples: config/samples.yaml
units: config/units.tsv

references:
    basepath: "path_to_references_data"
    provider: "_provider_"
    release: "_release_"

genome_fasta: "_genome_fasta_"

known_variants:
    dbsnp: "known_variants/dbSNP146_chr.vcf"
    hapmap: "known_variants/hapmap_3.3.hg19.sites.vcf"
    g1k: "known_variants/1000G_phase1.snps.high_confidence.hg19.sites.vcf"
    omni: "known_variants/1000G_omni2.5.hg19.sites.vcf"
    mills: "known_variants/Mills_and_1000G_gold_standard.indels.hg19.sites.vcf"
    ph1_indels: "known_variants/1000G_phase1.indels.hg19.sites.vcf"


params:
    bwa-mem:
        arguments: "-M"
        platform: "illumina"
    multiqc:
        arguments: ""
    trim_galore_pe:
        arguments: "--paired -q 20 "
    trim_galore_se:
        arguments: "-q 20 "
    picard_MarkDuplicates:
        arguments: "REMOVE_DUPLICATES=false ASSUME_SORTED=true CREATE_INDEX=true"
    picard_WGSMetrics:
        arguments: "MINIMUM_MAPPING_QUALITY=-1 MINIMUM_BASE_QUALITY=-1 READ_LENGTH=150 COUNT_UNPAIRED=true"
    gatk_BQSR:
        known_sites:
            - dbsnp
            - mills
            - ph1_indel



paths:
  workdir: "/path/to/workdir"
  results_dir: "/path/to/results_dir"
  tmp_dir: "/path/to/tmp_dir"